ovn-fake-multinode-utils/scripts/log-collector.sh
=> Collect OVS/OVN DBs at test completion.

browbeat-scenarios/osh_workload_incremental.json
=> Update rally scenario for new network policy tests.

browbeat-scenarios/switch-per-node-100.yml
=> Fix switch-per-node-100.yml scenario.

do.sh, ovn-fake-multinode-utils/playbooks/collect-logs.yml, ovn-fake-multinode-utils/playbooks/deploy-minimal.yml, ovn-fake-multinode-utils/scripts/perf.sh
collect perf results at the end of the test on the central node
=> collect perf results at the end of the test

README.md, browbeat-scenarios/osh_workload_incremental.json, browbeat-scenarios/switch-per-node-100.yml
Signed-off-by: Lorenzo Bianconi <lorenzo.bianconi@redhat.com>
=> Introduce perf parameters to osh_workload_incremental.json

do.sh
=> Force at most one instance of ovn-heater running.

do.sh
=> Add OS_IMAGE_OVERRIDE to explicitly set OS image.

do.sh
=> do.sh: Move to upstream ovn-scale-test, OVS2.14, OVN20.06.2.

do.sh, ovn-fake-multinode-utils/playbooks/install-dependencies.yml
Also, add the missing containers-common dependency.
=> Move to OVN 20.09.0.

browbeat-scenarios/osh_workload_incremental.json
=> Move non-OVN initialization out of test workload.

browbeat-scenarios/osh_workload_incremental.json
=> scenarios: Make datapath type configurable.

ovn-tester/ovn_stats.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
introduce test exception handling
=> ovn-tester: introduce test exception handling

ovn-tester/ovn_tester.py, test-scenarios/ovn-120.yml, test-scenarios/ovn-20.yml, test-scenarios/ovn-500.yml, test-scenarios/ovn-low-scale.yml
=> Introduce light-density test

ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py, test-scenarios/ovn-120.yml, test-scenarios/ovn-20.yml, test-scenarios/ovn-500.yml, test-scenarios/ovn-low-scale.yml
=> Heavy density test

ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py
=> ovn-tester: Enable trim-on-compaction for OVSDB servers.

ovn-tester/ovn_tester.py, test-scenarios/ovn-120.yml, test-scenarios/ovn-20.yml, test-scenarios/ovn-500.yml, test-scenarios/ovn-low-scale.yml
introduce cluster density test
=> ovn-tester: introduce cluster_density test

ovn-tester/ovn_load_balancer.py, ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
startup phase for cluster_density, density_light and density_heavy
=> Ovn tester batch

ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
=> ovn-tester: Add port security to pod LSPs.

ovn-tester/ovn_workload.py
This simulates what ovn-kubernetes does: port groups are created only
when the first network policy is added to the namespace.  Address sets
are created from the beginning however.
=> ovn-tester: Create namespace port groups only when enforcing policies.

ovn-tester/ovn_context.py, ovn-tester/ovn_stats.py
Also, declare an iteration "failed" if any of the routines failed during
that iteration.
=> ovn-tester: Log iteration result.

.github/workflows/test.yml, ovn-tester/ovn_load_balancer.py, ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py, ovn-tester/tests/cluster_density.py, ovn-tester/tests/density_heavy.py, ovn-tester/tests/density_light.py, ovn-tester/tests/netpol_cross_ns.py, ovn-tester/tests/netpol_multitenant.py, ovn-tester/tests/netpol_small.py
=> Enforce style checks.

README.md
=> README: Fix instructions about passwordless SSH.

README.md, do.sh, ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py, test-scenarios/ovn-etcd-low-scale.yml
Signed-off-by: Mohamed S. Mahmoud <mmahmoud@redhat.com>
=> Integrate ovsdb-etcd to ovn-heater and create etcd test scenario.

ovn-tester/ovn_context.py, ovn-tester/tests/cluster_density.py, ovn-tester/tests/density_heavy.py, ovn-tester/tests/density_light.py, ovn-tester/tests/netpol.py, ovn-tester/tests/netpol_cross_ns.py, ovn-tester/tests/netpol_multitenant.py
ovn-tester: move ext-cmd execution in ovn_context
=> ovn-tester: move ext-cmd execution in ovn_context

ovn-tester/tests/density_heavy.py, test-scenarios/ocp-120-density-heavy.yml, test-scenarios/ocp-20-density-heavy.yml, test-scenarios/ovn-low-scale.yml
=> density_heavy: Fix config defaults.

ovn-tester/tests/density_heavy.py
add  per-service lb for density-heavy
=> Density-heavy per service lb

.github/workflows/test.yml
=> Update GHA jobs to run on changes to branch 'main'.

ovn-tester/ovn_load_balancer.py, ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
This applies to all tests that use Cluster.provision_lb(), which today
corresponds to density-heavy and cluster-density.
=> Add load balancer groups.

ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py, ovn-tester/tests/cluster_density.py, ovn-tester/tests/density_heavy.py, ovn-tester/tests/density_light.py, ovn-tester/tests/netpol.py, ovn-tester/tests/netpol_cross_ns.py, ovn-tester/tests/netpol_large.py, ovn-tester/tests/netpol_multitenant.py, ovn-tester/tests/netpol_small.py
Add IPv6 support to base_cluster_bringup phase
=> ovn-tester: add IPv6 support

do.sh
If we managed to run the test and collect its logs it's good enough to
determine if the test passed or failed.  The post-processing stage
shouldn't fail but in case it does (e.g., because of a bug in the
processing tools) it should not trigger the whole test to fail.
Run the post-processing in a separate subshell with errexit disabled.
=> do.sh: Don't errexit in the post-processing stage.

.github/workflows/test.yml, ovn-fake-multinode-utils/generate-docker-cfg.py, ovn-fake-multinode-utils/generate-hosts.py, ovn-fake-multinode-utils/generate-podman-cfg.py, ovn-fake-multinode-utils/process-monitor.py, ovn-tester/ovn_context.py, ovn-tester/ovn_ext_cmd.py, ovn-tester/ovn_load_balancer.py, ovn-tester/ovn_sandbox.py, ovn-tester/ovn_stats.py, ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py, ovn-tester/tests/cluster_density.py, ovn-tester/tests/density_heavy.py, ovn-tester/tests/density_light.py, ovn-tester/tests/netpol.py, ovn-tester/tests/netpol_cross_ns.py, ovn-tester/tests/netpol_large.py, ovn-tester/tests/netpol_multitenant.py, ovn-tester/tests/netpol_small.py, utils/helpers.py, utils/latency.py, utils/process-stats.py
Reformat the codebase with Black
and add it to CI runs. To format
the files locally you can run:
black -l 79 -S $FILE
Signed-off-by: Ales Musil <amusil@redhat.com>
=> Reformat ovn-heater with Black

ovn-tester/ovn_utils.py, ovn-tester/tests/service_route.py, test-scenarios/ovn-low-scale.yml
=> ovn-tester: add service_route test

ovn-tester/tests/cluster_density.py, ovn-tester/tests/density_heavy.py, test-scenarios/ovn-low-scale.yml
Make the startup stages for cluster-density and density-heavy provision things in the same way as the "main" test stage does.
=> Realistic startup.

.cirrus.yml, README.md, do.sh, ovn-fake-multinode-utils/get-config-value.py, ovn-fake-multinode-utils/playbooks/deploy-minimal.yml, ovn-fake-multinode-utils/playbooks/install-dependencies.yml, ovn-fake-multinode-utils/process-monitor.py, ovn-fake-multinode-utils/translate_yaml.py, ovn-tester/ovn_tester.py
Please review commit by commit.
Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>
=> Introduce initial support for multiple distributions.

.github/pull_request_template.md, README.md
=> docs: Re-direct links: dceara --> ovn-org.

.cirrus.yml, do.sh, ovn-fake-multinode-utils/scripts/perf.sh, ovn-tester/ovn_ext_cmd.py, ovn-tester/ovn_workload.py, test-scenarios/ovn-low-scale.yml
Add support for flamegraph collection through ext_cmd.
=> Add support for flamegraph 

README.md
all installation and test steps should be run on ORCHESTRATOR node
=> README: make installation and test steps clearer

ovn-fake-multinode-utils/translate_yaml.py, ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py, test-scenarios/ovn-low-scale.yml
We only log Logical_Switch_Port and Port_Binding transactions for now but that should be enough for debugging.
=> ovn-tester: Add cluster config knob to enable transaction logging.

README.md, ovn-fake-multinode-utils/generate-hosts.py, ovn-fake-multinode-utils/playbooks/bringup-cluster.yml, ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py, physical-deployments/ci.yml, physical-deployments/physical-deployment.yml
=> Ovn ic central nodes deployment rework

ovn-tester/cms/ovn_kubernetes/tests/base_cluster_bringup.py
=> ovn-tester: do not create transit switch in non-ic mode
