browbeat-scenarios/osh_workload_incremental.json, browbeat-scenarios/switch-per-node-300.yml, browbeat-scenarios/switch-per-node-500.yml, browbeat-scenarios/switch-per-node-low-scale-batch2.yml, browbeat-scenarios/switch-per-node-low-scale.yml
By default we start all tests with NB/SB DBs clustered. Make
configuration less error prone by setting ovn_central_ip to point to all
central IPs by default.
=> Set ovn_central_ip to point to all central IPs by default.

do.sh
"git clone" uses the repo name as the default name for the directory
it creates.  This is right for the default repos, but users might
override the repo with one that has a different name, in which case
the default will be wrong.
By specifying the directory name explicitly like this, it will always
work properly.
I had this problem when I tried to use my ovs-reviews repo for OVS
and OVN.
Signed-off-by: Ben Pfaff <blp@ovn.org>
=> do.sh: Clone projects into correct directories.

do.sh, ovn-fake-multinode-utils/playbooks/configure-docker-registry.yml, ovn-fake-multinode-utils/playbooks/install-dependencies.yml
This enables users to use docker on platforms where docker is not
officially supported, e.g., RHEL8.
Also, remove dependency on docker-distribution. Instead just start a
container that runs the registry on the tester node.
=> do.sh: Use docker-ce when available.

README.md, browbeat-scenarios/osh_workload_incremental.json, browbeat-scenarios/switch-per-node-30-node-1000-pods.yml
Also make it configurable if logical ports should be bound to network
namespaces. In some cases, e.g., when testing ovn-northd performance,
this is not needed.
=> Add new "scale-pods" scenario.

browbeat-scenarios/osh_workload_incremental.json
Due to a problem in rally-ovs, a new persistent connection is created
for every new fake chassis.  This can cause problems at scale, e.g.,
running out of file descriptors while initiating 500 fake nodes.
For now disable batching.
This should be revisited once the rally-ovs persistent connection issue
is fixed.
=> Remove batching for initialization workload.

ovn-fake-multinode-utils/scripts/log-collector.sh
It's good to know what processes are running with their exact command
lines and how many resources they're using.  Fr example, it's very
important to know what is the current memory consumption per process in
the end of the test, e.g. if you're working on memory related
optimizations.
=> Collect information about running processes at test completion.

browbeat-scenarios/osh_workload_incremental.json
=> scenarios: Make logical-dp-groups and SB raft timeout configurable.

ovn-tester/ovn_load_balancer.py, ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
This is part one of a series that seeks to update the bring-up scenario to be closer to our scale testing goals.
In this series of commits:
Commit 1: Introduces a Load Balancer API.
Commit 2: Uses the API to create a cluster load balancer and add some initial VIPs to it.
These commits do not add per-node load balancers, nor do they update the cluster load balancers after initial creation. This is because the refactor that this patch is based off does not have the node-specific bring-up defined. This is best left until the rest of the code has been refactored.
=> Add Load Balancer API and use it to create cluster load balancer during cluster bring-up

ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py, test-scenarios/ovn-500.yml, test-scenarios/ovn-low-scale.yml
Allows scale testing OpenShift multitenant network policy-like
scenarios, for example, the equivalent of:
```
for i in range(n_namespaces):
create address set AS_ns_i
create port group PG_ns_i
if i < 200:
n_pods = 1 # 200 pods
elif i < 480:
n_pods = 5 # 1400 pods
elif i < 495:
n_pods = 20 # 300 pods
else:
n_pods = 100 # 500 pods
create n_pods
add n_pods to AS_ns_i
add n_pods to PG_ns_i
create acls:
to-lport, ip.src == $AS_ns_i && outport == @PG_ns_i, allow-related
to-lport, ip.src == {ip1, ip2, ip3} && outport == @PG_ns_i, allow-related
to-lport, ip.src == {ip1, ..., ip20} && outport == @PG_ns_i, allow-related
```
=> ovn-tester: Add multitenant network policy-like tests.

ovn-tester/ovn_load_balancer.py
There's no need to set all VIPs in a load balancer, it's enough to only
update the ones that actually changed.  Otherwise, ovn-nbctl ends up
creating increasingly large NB transactions when there's no need to do
that.
From what I see, OpenShift already does this, but needs more
investigation to confirm.
=> ovn_load_balancer: Only update changed VIPs.

ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
Make the DB inactivity probe configurable and set it to 60 seconds by
default to mimic what OpenShift does.
=> ovn-tester: Set NB/SB inactivity_probe.

ovn-tester/ovn_tester.py, ovn-tester/tests/cluster_density.py, ovn-tester/tests/density_heavy.py, ovn-tester/tests/density_light.py, ovn-tester/tests/netpol_multitenant.py
This change encapsulates tests into their own files. Each yaml section
in the configuration file corresponds to a module in the tests/
directory. This has the following advantages:
* The logic of individual tests can be contained within its own
module/class.
* The ovn_tester.py file can be made smaller, allowing for it to be the
orchestrator of tests, rather than holding test logic.
* New tests can be defined without needing to modify ovn_tester.py. Just
add the new module to tests/ and as long as the configuration is
present, the new test will be run.
* This allows for customized ordering of test scenarios.
* This allows for test scenarios to be skipped if desired.
In this change, the cluster bringup test is handled in a special way. It
is run directly in ovn_tester.py since it must be …
=> ovn-tester: Modularize test definitions.

ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py, test-scenarios/ocp-120-cluster-density-netdev.yml, test-scenarios/ocp-20-cluster-density-netdev.yml
=> ovn_tester: Make OVS datapath type configurable.

ovn-fake-multinode-utils/scripts/log-collector.sh, ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py, test-scenarios/ovn-low-scale.yml
Support for OVSDB Relays was added to OVS in commit:
https://github.com/openvswitch/ovs/commit/026c77c58ddba12ad81082ca27564ab9c33986bd
and will be part of 2.16 release.  Adding support to test 2-Tier Sb DB
setups with configurable number of relays.
Depends on a following change in ovn-fake-multinode:
https://github.com/ovn-org/ovn-fake-multinode/pull/44
=> ovn-tester: Add support for ovsdb relays.

ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py
Default 5000ms (as currently configured by OpenShift).
=> ovn-tester: Set northd probe interval.

ovn-tester/ovn_workload.py
This was erroring out since we were passing the representation of the
namedtuple for the router, rather than the router name.
=> ovn-tester: Use gw router name when setting lb_force_snat_ip.

do.sh, ovn-fake-multinode-utils/playbooks/deploy-minimal.yml
These changes make ovn-heater to respect docker containers not created by it.
For example, this is be required if user wants to run graphana/graphite container
on the central node (which is the same as management node in a single host setup).
=> ovn-heater: Be kind to third party containers

ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
OVN supports creating multiple gw router ports for a logical router.
This support was added to improve the scalability.  Make use of it.
A gateway chassis is created for each router port of the cluster router
with the node chassis as gateway chassis.
Signed-off-by: Numan Siddique <nusiddiq@redhat.com>
=> Set gateway chassis for each cluster router port.

ovn-tester/ovn_context.py, ovn-tester/ovn_sandbox.py, ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
'logging' module prints much more information including timestamps
which are useful while trying to match ovn-heater events with logs
from OVN daemons.
Multiline outputs from the sandbox execution are prefixed with "---\n",
because these doesn't look good when the first line is printed with all
the logging prefixes and the next ones are not.
Also, added a check that stderr is not empty to avoid printing blank
lines which are a bit annoying.
Some example:
```
2021-08-30 11:39:38,493 | ovn_context  |INFO| Context base_cluster_bringup, Iteration 1
2021-08-30 11:39:38,493 | ovn_workload |INFO| Connecting worker ovn-scale-1
2021-08-30 11:39:38,718 | ovn_sandbox  |INFO| ---
OVN remote = ssl:192.16.0.4:6642,ssl:192.16.0.5:6642,ssl:192.16.0.6:6642 …
```
=> ovn-tester: Use logging module instead of plain prints.

do.sh, utils/mine-db-poll-intervals.sh, utils/mine-poll-intervals.sh
This commit adds a couple of scripts that mines data about unreasonably
long poll intervals from logs and stores it in a human-readable format
with all the statistics including min, max, avg, 95 percentile, etc.
values per OVN daemon.  For databases it tries to exclude poll
intervals that involved compactions and also collects data about time
spent on compactions separately.  Logic for this is not ideal, but it
seems to work fine for most cases.
Statistics counted with 'datamash' utility which is a new dependency.
Example of the output:
```
Unreasonably long poll intervals:
---------------------------------------------------------------------
Count       Min        Max       Median      Mean   95 percentile
---------------------------------------------------------------------
1073.0 …
```
=> do.sh: Collect data about poll intervals and database compactions.

ovn-tester/ovn_workload.py, ovn-tester/tests/cluster_density.py, ovn-tester/tests/density_heavy.py
For cluster density tests, the code didn't provision a load balancer per
ns during the startup stage.
Also, per namespace load balancers were not added to gw routers.
=> Fix per-ns load balancer support.

ovn-tester/ovn_load_balancer.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
On scaled setups, since we moved to load balancer per namespace there
will be lots of load balancers that need to be bound to lots of node
gateway routers/switches.  Binding to one node at a time is just a waste
of time.  Change load balancer APIs to allow binding to multiple
routers/switches in one operation.
For example, on a 20 node cluster density test run (10 startup
iterations) this reduces the test runtime by ~4 minutes (~40%).
=> Batch load_balancer bind to switch/router operations.

ovn-tester/ovn_workload.py
For some reason the exact same veth creation command is run twice in a
row when provisioning. Adding some debugging, I saw the following:
2021-09-01 14:06:15,391 | ovn_sandbox  |WARNING| Command docker exec ovn-scale-1 ip link add veth0 type veth peer name veth1 exited with status 2
2021-09-01 14:06:15,391 | ovn_sandbox  |WARNING| stderr: RTNETLINK answers: File exists
The error is benign, but we may as well get rid of it.
=> ovn-tester: Don't try creating the veth twice.

ovn-tester/ovn_workload.py, ovn-tester/tests/cluster_density.py
In the cluster_density test, we create a list of build ports, followed
by other ports during an iteration. At the end of the iteration, we
unprovision the build ports.
If global configuration is set to clean up at the end of a test, we then
try to unprovision all ports in the namespace once the test completes.
The problem is, we already unprovisioned the build ports during each
iteration. The namespace doesn't know this, and it results in errors.
This commit adds a new method for Namespace to unprovision a subset of
ports. We now unprovision the build ports in the cluster_density test
using this method. Now when the test ends and the namespace is
unprovisioned, it only unprovisions the remaining ports.
Signed-off-by: Mark Michelson <mmichels@redhat.com>
=> ovn-tester: Unprovision build_ports via the namespace.

ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py
relay containers only run a southbound database. Therefore, when we try
to enable trim on compaction for the northbound database in that
container, it results in an error. The error is benign, but it still is
better not to issue a useless command.
This commit fixes the problem by separating relay containers from other
DB containers. This way, they can get special treatment if necessary. In
this particular case, the special treatment is not to try to configure a
non-existent database.
Signed-off-by: Mark Michelson <mmichels@redhat.com>
=> ovn-tester: Separate relays from other DBs.

ovn-tester/tests/density_heavy.py
We were incorrectly provisioning way too many backends for every load
balancer created in the "startup" stage.  We should instead provision
one backend every 'pods_vip_ratio' pods in 'n_startup'.
=> density_heavy: Fix startup stage.

do.sh
'master' branch of OVN is renamed to 'main'.
Signed-off-by: Numan Siddique <nusiddiq@redhat.com>
=> Change the default OVN_BRANCH value to 'main'

ovn-fake-multinode-utils/playbooks/deploy-minimal.yml
The cleanup was incorrect and was causing container images to be removed just before the test was started. Revert it to unblock tests.
=> Revert "deploy-minimal: Cleanup all container images and volumes."

do.sh, ovn-fake-multinode-utils/playbooks/deploy-minimal.yml, ovn-fake-multinode-utils/process-monitor.py, ovn-fake-multinode-utils/scripts/log-collector.sh, ovn-tester/ovn_workload.py, utils/process-stats.py
With this change the new process-monitor.py script is copied into
each container and started to collect RSS and CPU usage of all
OVS/OVN processes.  Later, log-collector will stop the monitoring
and will collect results as a process-stats.json file.  do.sh
script then uses process-stats.py script at the data mining stage
to produce html reports for master and worker nodes containing
RSS an CPU usage graphs.
The integration part is a bit sketchy.  Alternative is to avoid
modification of the ovn-tester itself and only deploy the
process monitor on the physical host.  This will make the code
a bit cleaner, but we'll loose an easy way to add container names
to process names.  Also, the monitor spends 0.5 seconds per process
to estimate the CPU usage.  More processes to track - less accurate …
=> Collect RSS and CPU usage for OVS/OVN processes.

do.sh
The 'head -3' command might close the pipe while grep is still
writing to it, causing a SIGPIPE, which in turn causes the script to
fail because we run 'do.sh' with 'pipefail' set.
=> do.sh: Gracefully deal with grep pipefail when processing stats.

test-scenarios/ocp-180-cluster-density.yml, test-scenarios/ocp-180-density-heavy.yml, test-scenarios/ocp-180-density-light.yml, test-scenarios/ocp-180-np-multitenant.yml, test-scenarios/ocp-60-cluster-density.yml, test-scenarios/ocp-60-density-heavy.yml, test-scenarios/ocp-60-density-light.yml, test-scenarios/ocp-60-np-multitenant.yml
Running tests at 20, 60, 120, 180, 250 node scales should help detect
whether OVN performance scales linearly or not.
=> ovn-tester: Add 60 and 180 node OCP like test scenarios.

ovn-tester/ovn_workload.py
Binding is one of the most heavy operations and it's not logged at the
moment.  We may not see any logs for a log time while ovn-heater is
binding thousands of ports during the test startup stage, for example.
=> ovn_workload: Log binding of a logical port.

do.sh
If there are no ovn/registry containers on a system, lookup will fail
and the 'pipefail' will fail the entire run.
If the registry container is stopped, it won't show up in the output
of a normal 'docker ps', but the subsequent 'docker run' will fail
to start container with the same name, so '--all' has to be used.
Also, if due to earlier failures everything is already checked out,
but the image doesn't exist, it will not be built.  So, we need to
check if the image is available and re-build if it is not.
=> do.sh: Fix initial installation.

do.sh, utils/latency.py
Difference per logical port between port being bound to the node
and ovn-controller marking it as ovn-installed, including usual
min, max, avg, 95%ile.  Ports that was never actually installed
are also counted.
Results are in the mined-data/binding-to-ovn-installed-latency.
The metric should be taken with a grain of salt, because ports
are bound (OVS port with iface-id created) after they were already
created in Nb DB.  And for bulk port creations, binding happens
in bulk as well afterward.  The value can be more or less treated
as an end to end OVN latency for ports created during the test
phase though.
Useful to spot issues like very high latency or ports not being
installed at all.
ovn-heater might be changed in the future to always bind ports
right after creation to make the metric …
=> do.sh: Add lport binding to ovn-installed latency to mined data.

ovn-tester/ovn_sandbox.py, ovn-tester/ovn_workload.py
Currently ovn-heater calls 'docker exec' via SSH connection to a
physical host every time it needs to execute any command inside
a container.  Just 'docker exec' itself adds anywhere from 150 to
500 ms of extra overhead to every call.
To avoid that overhead, creating a separate channel for each
container within a common SSH connection.  Using an interactive
shell emulator from the invoke_shell() method, invoking a docker
interactive shell.  Once this is done, we have a direct channel
to execute any commands inside of a container with only few
milliseconds of overhead (4-5 ms in practice).
Since it's not just a command execution API like paramiko's
exec_command(), but a real shell emulator, it's a bit trickier
to work with.  Shell sends back command prompts and everything
you send to it. …
=> sandbox: Speed up command execution by re-using docker exec shell.

ovn-tester/ovn_context.py, ovn-tester/ovn_tester.py, ovn-tester/tests/cluster_density.py, ovn-tester/tests/density_heavy.py, ovn-tester/tests/density_light.py, ovn-tester/tests/netpol.py, ovn-tester/tests/netpol_cross_ns.py, ovn-tester/tests/netpol_multitenant.py
Adding an extra 'ovn-nbctl sync' while exiting test contexts,
so previous test stages doesn't skew results for later ones.
=> ovn-tester: Wait for all changes to be applied before exiting context.

ovn-tester/ovn_context.py, ovn-tester/ovn_sandbox.py, ovn-tester/ovn_utils.py
Currently 'ovn-nbctl sync' is executed via Sandbox class that has a
default 60 second timeout on all operations.  This means that
synchronization longer than one minute will be terminated:
14:04:02 | ovn_context  |INFO| Waiting for the OVN state synchronization
14:05:02 | ovn_sandbox  |WARNING| Command
"ovn-nbctl -u /var/run/ovn/ovn-nbctl.ctl
--timeout=1800 --wait=hv sync ;"
timed out!
14:05:02 | ovn_sandbox  |INFO| Result: [''], Exit status: 42
Fix that by introducing a generic 'timeout' option to all Sandbox
derived run() methods.  Default value is 60 seconds, but can be
overwritten by the caller.  Currently only used for nbctl sync that
will have 30 minutes to complete.  Execution timeout set slightly
higher than nbctl timeout option to allow the nbctl call to terminate
itself …
=> ovn-tester: Fix nbctl sync timeout.

ovn-fake-multinode-utils/playbooks/deploy-minimal.yml
Without these changes the host will not be able to run more than
10-ish containers.  The default value for MaxSessions is only 10,
defualt value for fs.inotify.max_user_instances also allows to
start only 10-12 containers on the host:
ovn-scale-59: Failed to create control group inotify object: Too many open files
ovn-scale-59: Failed to allocate manager object: Too many open files
ovn-scale-59: [!!!!!!] Failed to allocate manager object.
Issues can be easily triggered by attempting to run 20 or 60
node tests on localhost.
Chosen values should allow to run any reasonable number of fake
nodes per physical machine.
=> Update maximum number of SSH sessions and fs notifiers

ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py
OpenShift is using northd parallelization with 4 threads by default.
ovn-heater should do that as well.  Can be configured by setting
'northd_threads' in the test yml.
=> ovn_tester: Enable northd parallelization.

ovn-fake-multinode-utils/playbooks/deploy-minimal.yml
In high-scale tests the kernel on central nodes complains:
kernel: neighbour: arp_cache: neighbor table overflow!
This is due to large number of incoming database connections from
all other nodes.  Setting up higher cache size to avoid the problem.
Values are taken from a live ovn-kubernetes cluster.
Not using ansible's 'sysctl' module to avoid setting these values
permanently.
=> Ensure the neighbor cache size on central nodes is sufficient

ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py
ovn-kubernetes sets different values for a lot of router options.
Fot example, it sets 'dynamic_neigh_routers' on all node gateway
routers.  This has a significant impact on the amount of logical
flows OVN generates.  For example, by enabling this option in
ovn-heater, number of logical flows in 500-node density-heavy
run is reduced from 790 K down to 290 K.  That has a significant
impact on the database size and the cluster operation.
Other options will also have impact on the actually generated
logical flows.
Values are taken from the current ovn-kubernetes.
Node gateway router:
https://github.com/ovn-org/ovn-kubernetes/blob/f78409cb6791225421c73936c6419d4483b14414/go-controller/pkg/ovn/gateway_init.go#L38
Cluster router:
https://github.com/ovn-org/ovn-kubernetes/blob/f78409cb6791225421c …
=> ovn_workload: Align router configuration with ovn-kubernetes.

.cirrus.yml, do.sh, physical-deployments/localhost.yml
Add a Cirrus CI configuration YAML file with the job to run a minimal
low-scale test.  It is practically not possible or extremely hard to
do the same in GitHub Actions for few reasons:
- In GHA we're already inside of a container.
- This container is ubuntu-based.
- ovn-heater dosn't support debian-based distributions so we need to
run a nested container.
- Using a 'container:' config we can run a fedora container, but the
container command is always overwritten, so no way to run a
container with systemd as init.
- I failed to start any container with systemd as init manually.
- 'runner' is not a root, most of the operations require 'sudo',
but we will ssh to localhost without using sudo afterwards, even
if the user is replaced with 'runner' in ansible configuration.
- Many more …
=> cirrus: Check low-scale run in Cirrus CI.

test-scenarios/ocp-500-cluster-density.yml, test-scenarios/ocp-500-density-heavy.yml, test-scenarios/ocp-500-density-light.yml, test-scenarios/ocp-500-np-multitenant.yml
'cluster-density' scenarios are a bit uneven, e.g. it jumps from 1000 runs to 4000 between 120 and 250 node.  Just doubling that value for 500-node case.
Other tests just scaled linearly according to values in smaller ones.
Signed-off-by: Ilya Maximets \<i.maximets@ovn.org\>
=> test-scenarios: Add 500-node cases.

do.sh
Monitor processes hold the health information in the process name. E.g.:
```
ovsdb-server: monitoring pid 349 (1 crashes: pid 211 died,
killed (Aborted), core dumped)
```
Grep out all such strings from the output of ps to a separate file to be able to quickly spot crashes at a glance.
Do not create a file if nothing to report.
Signed-off-by: Ilya Maximets \<i.maximets@ovn.org\>
=> do.sh: Mine data about crashed OVS/OVN daemons.

ovn-tester/tests/cluster_density.py
We don't wait for them to be up so it's possible that the port gets added and removed from the NB before ovn-controller has the chance to claim them.  That will mess up the 'ovn-installed' latency calculation as we expect all LSPs to be claimed eventually.
Reported-at: https://github.com/dceara/ovn-heater/pull/136#issuecomment-1276749002
=> cluster_density: Skip build pods in the startup stage.

.github/workflows/test.yml
The python 3.6 is no longer available with
latest Ubuntu (22.04.1) on Github actions.
=> Update python and black version on CI

ovn-tester/ovn_utils.py
ovn-kubernetes disables this option since:
https://github.com/ovn-org/ovn-kubernetes/pull/3400
=> ovn-tester: Disable neighbor_responder flows for LB VIPs on LR.

ovn-tester/ovn_utils.py
Setting all LB options the same way ovn-kuberneted does in a default configuration according to buildLB() function:
https://github.com/ovn-org/ovn-kubernetes/blob/a7e9e693db1b5c963655112257df112c80e1cbfe/go-controller/pkg/ovn/controller/services/loadbalancer.go#L293
The main impact might be from the 'reject' option that alters northd behavior in a few places.
=> ovn-tester: Align LB options with ovn-kubernetes.

.cirrus.yml
If the test script fails, it doesn't fail with an error code. It continues to gather logs and mine data, so we have a clean exit code in the end.
We look for iteration failures afterwards, but we don't look for hard failures in python code.
Fix that by grepping for python 'Traceback' and failing if it is found.
=> cirrus: Fail CI if there are python stack traces in the log.

.cirrus.yml, README.md, do.sh, ovn-fake-multinode-utils/playbooks/install-fake-multinode.yml
Instead of cloning the same repo from each physical host it can be copied from the orchestrator node, where we already have it.
Simultaneous git clone from multiple physical nodes frequently results in GitHub connection timeouts.
=> install-fake-multinode.yml: Copy ovn-fake-multinode from the orchestrator.

do.sh, ovn-fake-multinode-utils/translate_yaml.py, ovn-tester/ovn_tester.py, utils/requirements.txt
Test scenario configuration is fairly lean since all configuration values have some default value. In the good old days, the default values for configuration items could be dictated solely in ovn-tester.
With the containerization of the tester, now do.sh sometimes needs to use configuration values as well. This means that do.sh sometimes also needs to be able to use the default values. However, do.sh has no idea what these default values are, so they end up getting duplicated by developers.
This change seeks to solve this problem. A new python script is now the arbiter of default values. When running a test, do.sh will take the test configuration, run it through this script, and generate a yaml file that has all default values filled in. This is then passed to ovn-tester as the …
=> config: Centralize default YAML.

ovn-fake-multinode-utils/translate_yaml.py, ovn-tester/ovn_utils.py
ovn-tester is currently using .1, .2 and .3 IP addresses as ovn-remote while actual database servers are on .2, .3 and .4.  This is happening because calculate_default_node_remotes() doesn't take into account the tester itself that owns the .1 address.
Fixes: 4ad22627749c ("Use the first IP address in the node_net for the tester.")
=> ovn-tester: Fix miscalculated node remotes.

do.sh, ovn-fake-multinode-utils/playbooks/install-dependencies.yml
The functionality of built-in venv is enough for our use case.
Also, virtualenv is not available in some distributions (rhel9).
=> do.sh: Use built-in venv instead of virtualenv.

do.sh
Don't use `lsb_release` anymore and correctly detect Fedora/RHEL-like distro versions.
=> do.sh: Improve host OS distro detection.

ovn-tester/ovn_ext_cmd.py, test-scenarios/ovn-low-scale.yml
We're using a common interactive shell for command execution. Background commands may print something at unpredictable times messing up output from other commands and causing random failures.
Silence all background commands by default.  Also adding a --quiet option to perf invocations while at it.
=> ext_cmd: Silence background commands.

utils/mine-db-poll-intervals.sh
We only use egrep in one place, and it's not really needed there. egrep is deprecated and generates warnings:
`
egrep: warning: egrep is obsolescent; using grep -E
`
Also the second `\` in `\-\-` may lead to undefined behavior and generates a warning now:
`
grep: warning: stray \ before -
`
=> utils: Fix grep 3.8 warnings.

ovn-tester/ovn_utils.py
Python IDL reconnects on leadership transfer before receiving reply for an in-progress transaction.  But the transaction might, and likely will, actually succeed.  So the LB may already exist after re-connection. Let ovsdbapp know about that, so it doesn't throw exceptions when this happens.
This doesn't solve all the possible issues with other types of resources, but LBs are the most common after ports that already have a proper handling in place.
Closes: https://github.com/ovn-org/ovn-heater/issues/146
=> ovn-tester: Fix exceptions while adding LBs after leadership transfer.

.cirrus.yml, do.sh
22.10 is EOL and not usable in Cirrus CI anymore.  Also, ensure pip is installed in the venv on deb-based platforms too.
=> ci: Bump Ubuntu to 23.03 and ensure pip is installed.

README.md
Similar to WORKER and CENTRAL nodes, TESTER also contacts OVN databases and therefore requires additional interface connected to the shared network
=> Docs: Mention that TESTER node requires dedicated interface

ovn-tester/ovn_utils.py
Missing `execute()` calls in `OvnNbctl.acl_add()` method resulted in ACLs never getting created in OVN Northbound database.
Testing/Verification:
* Run ocp-20-np-multitenant test scenario which utilises ACLs
* Log into OVN ovn-central container on OVN-CENTRAL host
* Dump ACL table
* `ovsdb-client dump unix:/var/run/ovn/ovnnb_db.sock OVN_Northbound ACL`
Before this change the table would be empty during and after the test scenario.
=> NBCTL: Fix missing `execute()` when adding ACLs

ovn-tester/ovn_context.py, ovn-tester/ovn_ext_cmd.py, ovn-tester/ovn_load_balancer.py, ovn-tester/ovn_sandbox.py, ovn-tester/ovn_workload.py
We expect Python3 to be used and in Python3 all classes inherit from object.
Reported-at: https://github.com/ovn-org/ovn-heater/pull/173#discussion_r1325922500
=> treewide: Remove useless object inheritance.

README.md, do.sh
`refresh-tester` subcommand of `do.sh` triggers only rebuild of a tester container. It provides a faster way to apply/test your changes if you work only inside the `ovn-tester` package, and you don't want to rebuild OVN packages or fake-multinode image.
---
This is just something that I found handy in my workflow.
=> do.sh: Add `refresh-tester` subcommand.

ovn-fake-multinode-utils/translate_yaml.py, ovn-tester/cms/ovn_kubernetes/ovn_kubernetes.py, ovn-tester/cms/ovn_kubernetes/tests/base_cluster_bringup.py, ovn-tester/cms/ovn_kubernetes/tests/cluster_density.py, ovn-tester/cms/ovn_kubernetes/tests/density_heavy.py, ovn-tester/cms/ovn_kubernetes/tests/density_light.py, ovn-tester/cms/ovn_kubernetes/tests/netpol.py, ovn-tester/cms/ovn_kubernetes/tests/netpol_cross_ns.py, ovn-tester/cms/ovn_kubernetes/tests/netpol_large.py, ovn-tester/cms/ovn_kubernetes/tests/netpol_multitenant.py, ovn-tester/cms/ovn_kubernetes/tests/netpol_small.py, ovn-tester/cms/ovn_kubernetes/tests/service_route.py, ovn-tester/ovn_ext_cmd.py, ovn-tester/ovn_tester.py, ovn-tester/ovn_workload.py
Define explicit nodes for all components (central DBs, relays, etc.), avoid IP guesswork and fix a few bugs.
=> Refactor cluster bringup.

.cirrus.yml, do.sh, ovn-fake-multinode-utils/playbooks/bringup-cluster.yml, ovn-fake-multinode-utils/translate_yaml.py, ovn-tester/cms/ovn_kubernetes/ovn_kubernetes.py, ovn-tester/cms/ovn_kubernetes/tests/base_cluster_bringup.py, ovn-tester/cms/ovn_kubernetes/tests/cluster_density.py, ovn-tester/cms/ovn_kubernetes/tests/density_heavy.py, ovn-tester/cms/ovn_kubernetes/tests/density_light.py, ovn-tester/cms/ovn_kubernetes/tests/netpol.py, ovn-tester/cms/ovn_kubernetes/tests/netpol_cross_ns.py, ovn-tester/cms/ovn_kubernetes/tests/netpol_large.py, ovn-tester/cms/ovn_kubernetes/tests/netpol_multitenant.py, ovn-tester/cms/ovn_kubernetes/tests/netpol_small.py, ovn-tester/cms/ovn_kubernetes/tests/service_route.py, ovn-tester/ovn_context.py, ovn-tester/ovn_ext_cmd.py, ovn-tester/ovn_tester.py, ovn-tester/ovn_utils.py, ovn-tester/ovn_workload.py, test-scenarios/ovn-low-scale-ic.yml
Add ovn-ic support to ovn-tester.
=> ovn-tester: introduce ovn-ic

ovn-fake-multinode-utils/playbooks/bringup-cluster.yml
We accidentally only computed them for central_hosts but we actually need them on workers too.
Fixes: 29e078134421 ("ovn-tester: add the capability to run multiple independent clusters")
=> bringup-cluster: Compute central facts for all types of nodes.

ovn-tester/cms/ovn_kubernetes/ovn_kubernetes.py
=> Fix IC address set usage.

.cirrus.yml, Dockerfile, README.md, do.sh
Please review commit-by-commit.
This is a follow-up change after ovn-fake-multinode added support for ubuntu-baed builds (https://github.com/ovn-org/ovn-fake-multinode/pull/85)
=> do.sh: Add ability to run ovn-heater on Ubuntu

ovn-fake-multinode-utils/playbooks/install-dependencies.yml
If the package cache is not updated for example after a clean install, the `install-dependencies` playbook may fail with errors like this:
TASK [Install container command] ***************************
{"changed": false, "msg": "No package matching 'podman' is available"}
Use the `apt` build in ansible module and set `update_cache` to 'true' to fix this issue.
=> playbooks/dependencies: Update package cache on deb systems.

.cirrus.yml
The Ubuntu 23.04 went EOL, change the image to 23.10.
=> ci: Bump CirrusCI Ubuntu image version

do.sh
In case of a large number of availability zones the size of the resource usage report becomes unmanageable and browsers are not even able to open them.  For example, the size of the report on a 120 node cluster-density test is 166 MB.
Fix that the same way we do for workers - gather statistics only from the first 3 zones.
For the future we'll need to have aggregated stats in addition to these truncated ones, so we don't overlook potential issues and can compare cluster-wide resource usage with different number of zones.
Fixes: 40716b0bef06 ("ovn-tester: add the capability to deploy central components on multiple hv for ovn-ic")
=> do.sh: Fix bloating of the resource usage report for central nodes.

ovn-tester/cms/ovn_kubernetes/tests/density_heavy.py, ovn-tester/cms/ovn_kubernetes/tests/density_light.py, ovn-tester/ovn_utils.py
In this mode we should actually distribute the ports that are created in the startup stage between AZs (clusters) instead of creating all of them in all AZs.
Fixes: 2562afb45721 ("ovn-tester: extend density_light testing for ovn-ic")
Fixes: 84649236d689 ("ovn-tester: extend density_heavy for ovn-ic")
=> density_heavy: density_light: Fix startup stages when running in IC mode.

do.sh, ovn-fake-multinode-utils/process-monitor.py, utils/process-stats.py
This PR adds a new html report `resource-usage-report-aggregate.html` that contains graphs for aggregate memory and CPU usage per process type as well as numbers for peak memory and CPU usage of all OVN processes combined.
`pandas.DataFrame` does all the heavy lifting of data interpolation between uneven timestamps and aggregation across processes.
Closes: #195
=> Add aggregate resource usage graphs

README.md, do.sh
=> Use OVS main branch.

.cirrus.yml, ovn-fake-multinode-utils/translate_yaml.py
Southbound DB cluster tolerates 16 seconds of leader being unavailable.  It doesn't make sense for northd to be more sensitive.  And also, at 500+ node scale it can take more than 5 seconds to send a full database snapshot leading to constant re-connections and 100% CPU usage on Sb DB server preparing the same snapshot over and over.
CI updated to Ubuntu 24.04, because 23.10 is EoL and images for it are no longer available on GCP.  However, CI will still fail until https://github.com/ovn-org/ovn-fake-multinode/pull/90 is merged.
=> Fix default value for northd probe interval

ovn-fake-multinode-utils/scripts/log-collector.sh
Add ovs open-flows dump to log results folder
=> scripts: log-collector: Add ovs open-flows dump to log results

.github/workflows/test.yml, ovn-tester/cms/openstack/tests/base_openstack.py, ovn-tester/cms/ovn_kubernetes/tests/base_cluster_bringup.py, ovn-tester/ovn_workload.py
This removes python 3.7 from the lint jobs as this is not
supported anymore by the setup-python action.  It also adds the
newer versions supported by actions/setup-python@v5.
https://github.com/ovn-org/ovn-heater/actions/runs/13518101654/job/37770994792#step:3:7
While at it we bump the setup-python and checkout action versions
to the latest available (actions/checkout@v4 and
actions/setup-python@v5).
The new versions of flak8 report some additional style issues, those
are fixed by this commit too.
=> .github: Bump checkout and setup-python versions to latest.

ovn-tester/ovn_stats.py
Reported by flake8:
./ovn-tester/ovn_stats.py:32:5: F824 `global timed_functions` is
unused: name is never assigned in scope
https://github.com/ovn-org/ovn-heater/actions/runs/18093736973/
=> ovn_stats: Remove unused variable.

ovn-fake-multinode-utils/scripts/log-collector.sh
While dumping OF groups was limited to the last $limit containers on each node, that wasn't the case for OF rules.  Impose the same limit to avoid wasting disk space for mostly similar outputs from all virtual nodes on large scale (500 node) runs.
Also, reduce the $limit from 10 to 2 and pre-archive the dumped OF rules/groups text files for the same reason.
Fixes: 3fa30c388fb5 ("scripts: log-collector: Add ovs open-flows and group dump to log results")
=> log-collector.sh: Fix collection of OF rules.
